import React, { useState, useEffect } from "react";
import { Text, useApp } from "ink";
import zod from "zod";
import { argument } from "pastel";
import path from "node:path";
import { fileURLToPath } from "node:url";
import fs from "node:fs/promises";

export const description = "生成 Shell 自动补全脚本";

export const args = zod.tuple([
  zod
    .enum(["zsh", "bash", "fish"])
    .optional()
    .describe(
      argument({
        name: "shell",
        description: "Shell 类型 (zsh/bash/fish)，默认自动检测",
      }),
    ),
]);

type Props = { args: zod.infer<typeof args> };

async function scanCommands(): Promise<string[]> {
  const __dirname = path.dirname(fileURLToPath(import.meta.url));
  const commandsDir = path.resolve(__dirname, ".");
  const commands: string[] = [];

  async function walk(dir: string, prefix: string) {
    let entries;
    try {
      entries = await fs.readdir(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const e of entries) {
      if (e.name === "completion.js") continue;
      if (e.isDirectory()) {
        // Check for index.js (subcommand with default)
        try {
          await fs.access(path.join(dir, e.name, "index.js"));
          commands.push(prefix + e.name);
        } catch {
          // Not a standalone command, just a namespace
        }
        await walk(path.join(dir, e.name), prefix + e.name + " ");
      } else if (e.name.endsWith(".js") && e.name !== "index.js") {
        commands.push(prefix + e.name.replace(/\.js$/, ""));
      }
    }
  }

  await walk(commandsDir, "");
  return commands.sort();
}

function buildTree(commands: string[]): Map<string, string[]> {
  const tree = new Map<string, string[]>();
  for (const cmd of commands) {
    const parts = cmd.split(" ");
    for (let i = 0; i < parts.length; i++) {
      const parent = parts.slice(0, i).join(" ") || "__root__";
      const child = parts[i]!;
      if (!tree.has(parent)) tree.set(parent, []);
      const children = tree.get(parent)!;
      if (!children.includes(child)) children.push(child);
    }
  }
  return tree;
}

function generateZsh(commands: string[]): string {
  const tree = buildTree(commands);
  const topLevel = tree.get("__root__") ?? [];

  // Collect parents that have nested children (e.g. "guild" has "channel" which has sub-commands)
  const nestedParents = new Set<string>();
  for (const parent of tree.keys()) {
    if (parent === "__root__") continue;
    const depth = parent.split(" ").length;
    if (depth >= 2) {
      nestedParents.add(parent.split(" ")[0]!);
    }
  }

  let script = `#compdef icqq
# Auto-generated by: icqq completion zsh
# Add to your .zshrc: eval "$(icqq completion zsh)"

_icqq() {
  local -a commands
  local curcontext="$curcontext" state

  _arguments -C \\
    '-u[指定操作账号]:uin:' \\
    '--uin[指定操作账号]:uin:' \\
    '--json[JSON 格式输出]' \\
    '1:command:->cmd' \\
    '*::arg:->args'

  case "$state" in
    cmd)
      commands=(
`;
  for (const cmd of topLevel) {
    script += `        '${cmd}'\n`;
  }
  script += `      )
      _describe 'icqq command' commands
      ;;
    args)
      case "$words[1]" in
`;

  for (const [parent, children] of tree) {
    if (parent === "__root__") continue;
    if (!parent.includes(" ")) {
      if (nestedParents.has(parent)) {
        // This parent has nested sub-sub-commands, dispatch further
        script += `        ${parent})
          case "$words[2]" in
`;
        // Find level-2 children that have their own children
        for (const child of children) {
          const subKey = `${parent} ${child}`;
          const grandchildren = tree.get(subKey);
          if (grandchildren && grandchildren.length > 0) {
            script += `            ${child})
              local -a subsub
              subsub=(${grandchildren.map((c) => `'${c}'`).join(" ")})
              _describe 'subcommand' subsub
              ;;
`;
          }
        }
        script += `            *)
              local -a sub
              sub=(${children.map((c) => `'${c}'`).join(" ")})
              _describe 'subcommand' sub
              ;;
          esac
          ;;
`;
      } else {
        script += `        ${parent})
          local -a sub
          sub=(${children.map((c) => `'${c}'`).join(" ")})
          _describe 'subcommand' sub
          ;;
`;
      }
    }
  }

  script += `      esac
      ;;
  esac
}

compdef _icqq icqq
`;
  return script;
}

function generateBash(commands: string[]): string {
  const tree = buildTree(commands);
  const topLevel = tree.get("__root__") ?? [];

  let script = `# Auto-generated by: icqq completion bash
# Add to your .bashrc: eval "$(icqq completion bash)"

_icqq() {
  local cur prev words cword
  _init_completion || return

  if [[ $cword -eq 1 ]]; then
    COMPREPLY=($(compgen -W "${topLevel.join(" ")}" -- "$cur"))
    return
  fi

  case "\${words[1]}" in
`;

  for (const [parent, children] of tree) {
    if (parent === "__root__") continue;
    if (!parent.includes(" ")) {
      script += `    ${parent})
      COMPREPLY=($(compgen -W "${children.join(" ")}" -- "$cur"))
      ;;
`;
    }
  }

  script += `  esac
}

complete -F _icqq icqq
`;
  return script;
}

function generateFish(commands: string[]): string {
  const tree = buildTree(commands);

  let script = `# Auto-generated by: icqq completion fish
# Add to config.fish: icqq completion fish | source

`;

  const topLevel = tree.get("__root__") ?? [];
  for (const cmd of topLevel) {
    script += `complete -c icqq -n '__fish_use_subcommand' -a '${cmd}'\n`;
  }
  script += "\n";

  for (const [parent, children] of tree) {
    if (parent === "__root__") continue;
    if (!parent.includes(" ")) {
      for (const child of children) {
        script += `complete -c icqq -n '__fish_seen_subcommand_from ${parent}' -a '${child}'\n`;
      }
    }
  }

  return script;
}

export default function Completion({ args: [shell] }: Props) {
  const { exit } = useApp();
  const [output, setOutput] = useState("");
  const [error, setError] = useState("");

  const resolvedShell =
    shell ?? (process.env.SHELL?.includes("zsh") ? "zsh" : process.env.SHELL?.includes("fish") ? "fish" : "bash");

  useEffect(() => {
    void (async () => {
      try {
        const commands = await scanCommands();
        switch (resolvedShell) {
          case "zsh":
            setOutput(generateZsh(commands));
            break;
          case "bash":
            setOutput(generateBash(commands));
            break;
          case "fish":
            setOutput(generateFish(commands));
            break;
        }
      } catch (e) {
        setError(e instanceof Error ? e.message : String(e));
      }
    })();
  }, [resolvedShell]);

  useEffect(() => {
    if (output || error) {
      if (output) process.stdout.write(output);
      if (error) process.exitCode = 1;
      const timer = setTimeout(() => exit(), 0);
      return () => clearTimeout(timer);
    }
  }, [output, error, exit]);

  if (error) return <Text color="red">✖ {error}</Text>;
  return null;
}
