/**
 * 半自动生成 MCP action ↔ CLI 对照表（skills/icqq/references/mcp-cli-map.md）
 *
 * 用法:
 *   pnpm generate:skill-map          # 写入文件
 *   pnpm generate:skill-map --check  # 校验生成物与源码一致（CI）
 */
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const OUTPUT = path.join(ROOT, "skills/icqq/references/mcp-cli-map.md");

const HEADER = `<!-- DO NOT EDIT: generated by scripts/generate-skill-mcp-map.ts -->
`;

type ActionHint = { description: string; paramsHint?: string };

async function readText(rel: string): Promise<string> {
  return fs.readFile(path.join(ROOT, rel), "utf-8");
}

function parseActionStrings(protocolSource: string): Map<string, string> {
  const map = new Map<string, string>();
  const re = /^\s+([A-Z0-9_]+):\s*"([^"]+)"/gm;
  for (const match of protocolSource.matchAll(re)) {
    map.set(match[1]!, match[2]!);
  }
  return map;
}

function parseActionHints(source: string): Map<string, ActionHint> {
  const hints = new Map<string, ActionHint>();
  const blockRe =
    /\[Actions\.([A-Z0-9_]+)\]:\s*\{([^}]*)\}/gs;
  for (const match of source.matchAll(blockRe)) {
    const enumKey = match[1]!;
    const body = match[2]!;
    const desc = body.match(/description:\s*"([^"]*)"/)?.[1] ?? enumKey;
    const params = body.match(/paramsHint:\s*"([^"]*)"/)?.[1];
    hints.set(enumKey, { description: desc, paramsHint: params });
  }
  return hints;
}

function parseMcpBlocked(source: string): Set<string> {
  const blocked = new Set<string>();
  const section = source.match(
    /export const MCP_BLOCKED_ACTIONS = new Set<string>\(\[([\s\S]*?)\]\)/,
  )?.[1];
  if (!section) return blocked;
  for (const match of section.matchAll(/Actions\.([A-Z0-9_]+)/g)) {
    blocked.add(match[1]!);
  }
  return blocked;
}

async function scanCliCommands(
  actionEnumToValue: Map<string, string>,
): Promise<Map<string, string[]>> {
  const commandsDir = path.join(ROOT, "src/commands");
  const actionToCli = new Map<string, string[]>();

  async function walk(dir: string): Promise<void> {
    const entries = await fs.readdir(dir, { withFileTypes: true });
    for (const entry of entries) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        await walk(full);
        continue;
      }
      if (!entry.name.endsWith(".tsx")) continue;
      const source = await fs.readFile(full, "utf-8");
      const actionMatch = source.match(/action=\{Actions\.([A-Z0-9_]+)\}/);
      if (!actionMatch) continue;

      const enumKey = actionMatch[1]!;
      const action = actionEnumToValue.get(enumKey);
      if (!action) continue;

      let rel = path.relative(commandsDir, full).replace(/\.tsx$/, "");
      if (rel.endsWith("/index")) {
        rel = rel.slice(0, -"/index".length);
      } else if (rel === "index") {
        rel = "";
      }
      const cli = rel ? `icqq ${rel.replace(/\\/g, "/").replace(/\//g, " ")}` : "icqq";

      const list = actionToCli.get(action) ?? [];
      if (!list.includes(cli)) {
        list.push(cli);
        actionToCli.set(action, list.sort());
      }
    }
  }

  await walk(commandsDir);
  return actionToCli;
}

function renderMarkdown(
  rows: Array<{
    action: string;
    description: string;
    paramsHint: string;
    cli: string;
    mcp: string;
  }>,
): string {
  const lines = [
    HEADER.trimEnd(),
    "",
    "# MCP action ↔ CLI 对照",
    "",
    "由 `pnpm generate:skill-map` 从 `action-hints.ts` 与 `src/commands/**` 生成。",
    "MCP 调用前先 `icqq_list_actions`；下表 CLI 列可能有多个命令映射同一 action。",
    "",
    "| MCP action | 说明 | params 提示 | CLI | MCP |",
    "|------------|------|-------------|-----|-----|",
  ];

  for (const row of rows) {
    lines.push(
      `| \`${row.action}\` | ${row.description} | ${row.paramsHint} | ${row.cli} | ${row.mcp} |`,
    );
  }

  lines.push("");
  return lines.join("\n");
}

export async function generateSkillMcpMap(): Promise<string> {
  const [protocolSource, hintsSource, metaSource] = await Promise.all([
    readText("src/daemon/protocol.ts"),
    readText("src/daemon/action-hints.ts"),
    readText("src/daemon/action-meta.ts"),
  ]);

  const actionEnumToValue = parseActionStrings(protocolSource);
  const hints = parseActionHints(hintsSource);
  const blockedEnums = parseMcpBlocked(metaSource);
  const blockedActions = new Set(
    [...blockedEnums]
      .map((key) => actionEnumToValue.get(key))
      .filter((v): v is string => Boolean(v)),
  );
  const cliMap = await scanCliCommands(actionEnumToValue);

  const rows = [...actionEnumToValue.entries()]
    .map(([enumKey, action]) => {
      const hint = hints.get(enumKey);
      const cliList = cliMap.get(action) ?? [];
      return {
        action,
        description: hint?.description ?? action,
        paramsHint: hint?.paramsHint ?? "—",
        cli: cliList.length > 0 ? cliList.map((c) => `\`${c}\``).join("<br>") : "—",
        mcp: blockedActions.has(action) ? "禁止" : "允许",
      };
    })
    .sort((a, b) => a.action.localeCompare(b.action));

  return renderMarkdown(rows);
}

async function main() {
  const check = process.argv.includes("--check");
  const content = await generateSkillMcpMap();

  if (check) {
    let existing: string;
    try {
      existing = await fs.readFile(OUTPUT, "utf-8");
    } catch {
      console.error(`[generate-skill-map] 缺少 ${OUTPUT}，请先运行 pnpm generate:skill-map`);
      process.exit(1);
    }
    if (existing !== content) {
      console.error(
        "[generate-skill-map] mcp-cli-map.md 已过期，请运行 pnpm generate:skill-map 并提交",
      );
      process.exit(1);
    }
    console.log("[generate-skill-map] mcp-cli-map.md 已是最新");
    return;
  }

  await fs.mkdir(path.dirname(OUTPUT), { recursive: true });
  await fs.writeFile(OUTPUT, content, "utf-8");
  console.log(`[generate-skill-map] 已写入 ${OUTPUT}`);
}

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
